version: '3'
services:
  app:
    image: 'node:latest'
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm ci && npm start"
    ports:
      - '1000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
